name: PR Title Validation
on:
  workflow_call:
    secrets:
      token:
        required: true
jobs:
  conventional-commits:
    if:  startsWith(github.head_ref, 'develop/')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "La branche cible de cette PR est ${github.head_ref}"
